# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
cache: cocoapods
osx_image: xcode8.3
# podfile: Example/Podfile

rvm:
- 2.2.2
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild clean test -workspace Example/MBCircularProgressBar.xcworkspace -scheme MBCircularProgressBar-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s' | xcpretty -c
- pod lib lint --quick
