# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

pod 'SVProgressHUD'
pod 'MJExtension'
pod 'MJRefresh'
pod 'Masonry'
pod 'SDCycleScrollView'
pod 'FMDB'
pod 'ZYCornerRadius'
pod 'SDWebImage' ,"3.8.2"
pod 'ZXingObjC'
pod 'TZImagePickerController'
pod 'IQKeyboardManager'

target 'CDDStoreDemo' do


end
